
import 'package:ewallet_app/constants/img_api.dart';
import 'package:ewallet_app/models/vendor.dart';
import 'package:flutter/material.dart';

enum CreditType { coin, diamond, money }

class Credit {
  final String id;
  final double amount;
  final String? description;
  final String? thumb;
  final IconData icon;
  final Vendor? vendor;
  final String category;
  final String? groupName;
  final CreditType type;
  final String unit;
  final double price;
  final double discount;
  final bool isPromo;
  final double points;
  final String? timeleft;

  Credit({
    required this.id,
    required this.amount,
    this.description,
    this.thumb,
    this.icon = Icons.monetization_on,
    this.vendor,
    required this.category,
    this.groupName,
    this.type = CreditType.coin,
    this.unit = 'Credit',
    required this.price,
    this.discount = 0,
    this.isPromo = false,
    required this.points,
    this.timeleft,
  });
}

final List<Credit> appCredits = [
  Credit(
    id: '1',
    amount: 12,
    thumb: ImgApi.photo[261],
    vendor: vendorList[8],
    category: 'apps',
    unit: 'coins',
    type: CreditType.coin,
    price: 2,
    points: 10,
    discount: 4,
    isPromo: true,
    timeleft: '2d 3h',
  ),
  Credit(
    id: '2',
    amount: 34,
    thumb: ImgApi.photo[262],
    vendor: vendorList[8],
    category: 'apps',
    unit: 'coins',
    type: CreditType.coin,
    price: 5,
    points: 10,
    discount: 4,
    isPromo: true,
    timeleft: '2d 3h',
  ),
  Credit(
    id: '3',
    amount: 50,
    thumb: ImgApi.photo[263],
    vendor: vendorList[8],
    category: 'apps',
    unit: 'coins',
    type: CreditType.coin,
    price: 8,
    points: 10,
  ),
  Credit(
    id: '4',
    amount: 100,
    thumb: ImgApi.photo[264],
    vendor: vendorList[8],
    category: 'apps',
    unit: 'coins',
    type: CreditType.coin,
    price: 10,
    points: 10,
  ),
  Credit(
    id: '5',
    amount: 120,
    thumb: ImgApi.photo[265],
    vendor: vendorList[8],
    category: 'apps',
    unit: 'coins',
    type: CreditType.coin,
    price: 2,
    points: 12,
    discount: 10,
    isPromo: true,
    timeleft: '2d 3h',
  ),
  Credit(
    id: '6',
    amount: 150,
    thumb: ImgApi.photo[266],
    vendor: vendorList[8],
    category: 'apps',
    unit: 'coins',
    type: CreditType.coin,
    price: 150,
    points: 10,
    discount: 10,
    isPromo: true,
    timeleft: '2d 3h',
  ),
  Credit(
    id: '7',
    amount: 200,
    thumb: ImgApi.photo[267],
    vendor: vendorList[8],
    category: 'apps',
    unit: 'coins',
    type: CreditType.coin,
    price: 8,
    points: 10,
  ),
  Credit(
    id: '8',
    amount: 300,
    thumb: ImgApi.photo[268],
    vendor: vendorList[8],
    category: 'apps',
    unit: 'coins',
    type: CreditType.coin,
    price: 10,
    points: 10,
  ),
];

final List<Credit> electricCredits = [
  Credit(
    id: '1',
    amount: 5,
    icon: Icons.bolt,
    unit: 'kWh',
    category: 'electric',
    type: CreditType.money,
    price: 6,
    points: 10,
  ),
  Credit(
    id: '2',
    amount: 10,
    unit: 'kWh',
    icon: Icons.bolt,
    category: 'electric',
    type: CreditType.money,
    price: 11,
    points: 10,
  ),
  Credit(
    id: '3',
    amount: 30,
    icon: Icons.bolt,
    unit: 'kWh',
    category: 'electric',
    type: CreditType.money,
    price: 31,
    points: 10,
  ),
  Credit(
    id: '4',
    amount: 50,
    icon: Icons.bolt,
    unit: 'kWh',
    category: 'electric',
    type: CreditType.money,
    price: 50,
    points: 10,
  ),
  Credit(
    id: '5',
    amount: 100,
    icon: Icons.bolt,
    unit: 'kWh',
    category: 'electric',
    type: CreditType.money,
    price: 100,
    points: 10,
  ),
  Credit(
    id: '6',
    amount: 200,
    icon: Icons.bolt,
    unit: 'kWh',
    category: 'electric',
    type: CreditType.money,
    price: 200,
    points: 10,
  ),
  Credit(
    id: '7',
    amount: 300,
    icon: Icons.bolt,
    unit: 'kWh',
    category: 'electric',
    type: CreditType.money,
    price: 300,
    points: 10,
  ),
  Credit(
    id: '8',
    amount: 500,
    icon: Icons.bolt,
    unit: 'kWh',
    category: 'electric',
    type: CreditType.money,
    price: 500,
    points: 10,
  ),
];

final List<Credit> gameCredits = [
  Credit(
    id: '1',
    amount: 10,
    thumb: ImgApi.photo[297],
    icon: Icons.diamond,
    unit: 'diamonds',
    vendor: vendorList[33],
    category: 'game',
    type: CreditType.diamond,
    price: 2,
    points: 10,
  ),
  Credit(
    id: '2',
    amount: 30,
    thumb: ImgApi.photo[297],
    icon: Icons.diamond,
    unit: 'diamonds',
    vendor: vendorList[33],
    category: 'game',
    type: CreditType.diamond,
    price: 5,
    points: 10,
    discount: 5,
    isPromo: true,
    timeleft: '2d 3h'
  ),
  Credit(
    id: '3',
    amount: 100,
    thumb: ImgApi.photo[297],
    icon: Icons.diamond,
    unit: 'diamonds',
    vendor: vendorList[33],
    category: 'game',
    type: CreditType.diamond,
    price: 10,
    points: 10,
    discount: 5,
    isPromo: true,
    timeleft: '2d 3h'
  ),
  Credit(
    id: '4',
    amount: 155,
    thumb: ImgApi.photo[297],
    icon: Icons.diamond,
    unit: 'diamonds',
    vendor: vendorList[33],
    category: 'game',
    type: CreditType.diamond,
    price: 15,
    points: 10,
    discount: 5,
    isPromo: true,
    timeleft: '2d 3h'
  ),
  Credit(
    id: '5',
    amount: 210,
    thumb: ImgApi.photo[297],
    icon: Icons.diamond,
    unit: 'diamonds',
    vendor: vendorList[33],
    category: 'game',
    type: CreditType.diamond,
    price: 18,
    points: 10,
  ),
  Credit(
    id: '6',
    amount: 275,
    thumb: ImgApi.photo[297],
    icon: Icons.diamond,
    unit: 'diamonds',
    vendor: vendorList[33],
    category: 'game',
    type: CreditType.diamond,
    price: 15,
    points: 10,
    discount: 5,
    isPromo: true,
    timeleft: '2d 3h'
  ),
  Credit(
    id: '7',
    amount: 305,
    thumb: ImgApi.photo[297],
    icon: Icons.diamond,
    unit: 'diamonds',
    vendor: vendorList[33],
    category: 'game',
    type: CreditType.diamond,
    price: 25,
    points: 10,
  ),
  Credit(
    id: '8',
    amount: 360,
    thumb: ImgApi.photo[297],
    icon: Icons.diamond,
    unit: 'diamonds',
    vendor: vendorList[33],
    category: 'game',
    type: CreditType.diamond,
    price: 35,
    points: 10,
    discount: 5,
    isPromo: true,
    timeleft: '2d 3h'
  ),
];

final List<Credit> entertainmentCredits = [
  Credit(
    id: '1',
    amount: 10,
    description: '3 Days',
    thumb: ImgApi.photo[288],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[27],
    category: 'entertainment',
    type: CreditType.coin,
    price: 10,
    points: 10,
    isPromo: true,
    discount: 5,
    timeleft: '2d 3h',
  ),
  Credit(
    id: '2',
    amount: 20,
    description: '3 Days',
    thumb: ImgApi.photo[288],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[27],
    category: 'entertainment',
    type: CreditType.coin,
    price: 20,
    points: 10,
    isPromo: true,
    discount: 5,
    timeleft: '2d 3h',
  ),
  Credit(
    id: '3',
    amount: 30,
    description: '7 Days',
    thumb: ImgApi.photo[288],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[27],
    category: 'entertainment',
    type: CreditType.coin,
    price: 30,
    points: 10,
  ),
  Credit(
    id: '4',
    amount: 40,
    description: '7 Days',
    thumb: ImgApi.photo[288],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[27],
    category: 'entertainment',
    type: CreditType.coin,
    price: 40,
    points: 10,
  ),
  Credit(
    id: '5',
    amount: 50,
    description: '15 Days',
    thumb: ImgApi.photo[288],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[27],
    category: 'entertainment',
    type: CreditType.coin,
    price: 50,
    points: 10,
    isPromo: true,
    discount: 5,
    timeleft: '2d 3h',
  ),
  Credit(
    id: '6',
    amount: 60,
    description: '15 Days',
    thumb: ImgApi.photo[288],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[27],
    category: 'entertainment',
    type: CreditType.coin,
    price: 60,
    points: 10,
  ),
  Credit(
    id: '7',
    amount: 70,
    description: '15 Days',
    thumb: ImgApi.photo[288],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[27],
    category: 'entertainment',
    type: CreditType.coin,
    price: 70,
    points: 10,
    isPromo: true,
    discount: 5,
    timeleft: '2d 3h',
  ),
  Credit(
    id: '8',
    amount: 80,
    description: '28 Days',
    thumb: ImgApi.photo[288],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[27],
    category: 'entertainment',
    type: CreditType.coin,
    price: 80,
    points: 10,
  ),
  Credit(
    id: '9',
    amount: 90,
    description: '28 Days',
    thumb: ImgApi.photo[288],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[27],
    category: 'entertainment',
    type: CreditType.coin,
    price: 90,
    points: 10,
    isPromo: true,
    discount: 5,
    timeleft: '2d 3h',
  ),
  Credit(
    id: '10',
    amount: 100,
    description: '28 Days',
    thumb: ImgApi.photo[288],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[27],
    category: 'entertainment',
    type: CreditType.coin,
    price: 100,
    points: 10,
  ),
];

final List<Credit> educationCredits = [
  Credit(
    id: '1',
    amount: 10,
    description: '3 Days',
    thumb: ImgApi.photo[279],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[18],
    category: 'education',
    type: CreditType.coin,
    price: 10,
    points: 10,
    isPromo: true,
    discount: 5,
    timeleft: '2d 3h',
  ),
  Credit(
    id: '2',
    amount: 20,
    description: '3 Days',
    thumb: ImgApi.photo[279],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[18],
    category: 'education',
    type: CreditType.coin,
    price: 20,
    points: 10,
    isPromo: true,
    discount: 5,
    timeleft: '2d 3h',
  ),
  Credit(
    id: '3',
    amount: 30,
    description: '3 Days',
    thumb: ImgApi.photo[279],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[18],
    category: 'education',
    type: CreditType.coin,
    price: 30,
    points: 10,
  ),
  Credit(
    id: '4',
    amount: 40,
    description: '8 Days',
    thumb: ImgApi.photo[279],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[18],
    category: 'education',
    type: CreditType.coin,
    price: 40,
    points: 10,
  ),
  Credit(
    id: '5',
    amount: 50,
    description: '10 Days',
    thumb: ImgApi.photo[279],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[18],
    category: 'education',
    type: CreditType.coin,
    price: 50,
    points: 10,
    isPromo: true,
    discount: 5,
    timeleft: '2d 3h',
  ),
  Credit(
    id: '6',
    amount: 60,
    description: '10 Days',
    thumb: ImgApi.photo[279],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[18],
    category: 'education',
    type: CreditType.coin,
    price: 60,
    points: 10,
    isPromo: true,
    discount: 5,
    timeleft: '2d 3h',
  ),
  Credit(
    id: '7',
    amount: 70,
    description: '15 Days',
    thumb: ImgApi.photo[279],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[18],
    category: 'education',
    type: CreditType.coin,
    price: 70,
    points: 10,
    isPromo: true,
    discount: 5,
    timeleft: '2d 3h',
  ),
  Credit(
    id: '8',
    amount: 80,
    description: '15 Days',
    thumb: ImgApi.photo[279],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[18],
    category: 'education',
    type: CreditType.coin,
    price: 80,
    points: 10,
  ),
  Credit(
    id: '9',
    amount: 90,
    description: '28 Days',
    thumb: ImgApi.photo[279],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[18],
    category: 'education',
    type: CreditType.coin,
    price: 90,
    points: 10,
    isPromo: true,
    discount: 5,
    timeleft: '2d 3h',
  ),
  Credit(
    id: '10',
    amount: 100,
    description: '28 Days',
    thumb: ImgApi.photo[279],
    icon: Icons.motion_photos_on,
    unit: 'coins',
    vendor: vendorList[18],
    category: 'education',
    type: CreditType.coin,
    price: 100,
    points: 10,
    isPromo: true,
    discount: 5,
    timeleft: '2d 3h',
  ),
];

final List<Credit> mobileCredits = [
  Credit(
    id: '1',
    amount: 10,
    description: '7 Days',
    unit: 'Credit',
    thumb: ImgApi.photo[328],
    vendor: vendorList[67],
    category: 'mobile',
    type: CreditType.money,
    price: 11,
    points: 10,
    discount: 10,
    isPromo: true,
    timeleft: '2h 30m',
  ),
  Credit(
    id: '2',
    amount: 20,
    description: '7 Days',
    unit: 'Credit',
    thumb: ImgApi.photo[328],
    vendor: vendorList[67],
    category: 'mobile',
    type: CreditType.money,
    price: 21,
    points: 10,
    discount: 8,
    isPromo: true,
    timeleft: '2h 30m',
  ),
  Credit(
    id: '3',
    amount: 30,
    description: '7 Days',
    unit: 'Credit',
    thumb: ImgApi.photo[328],
    vendor: vendorList[67],
    category: 'mobile',
    type: CreditType.money,
    price: 31,
    points: 10,
  ),
  Credit(
    id: '4',
    amount: 40,
    description: '14 Days',
    unit: 'Credit',
    thumb: ImgApi.photo[328],
    vendor: vendorList[67],
    category: 'mobile',
    type: CreditType.money,
    price: 41,
    points: 10,
  ),
  Credit(
    id: '5',
    amount: 50,
    description: '14 Days',
    unit: 'Credit',
    thumb: ImgApi.photo[328],
    vendor: vendorList[67],
    category: 'mobile',
    type: CreditType.money,
    price: 50,
    points: 10,
  ),
  Credit(
    id: '6',
    amount: 60,
    description: '14 Days',
    thumb: ImgApi.photo[328],
    unit: 'Credit',
    vendor: vendorList[67],
    category: 'mobile',
    type: CreditType.money,
    price: 60,
    points: 10,
    discount: 8,
    isPromo: true,
    timeleft: '2h 30m',
  ),
  Credit(
    id: '7',
    amount: 70,
    description: '30 Days',
    thumb: ImgApi.photo[328],
    unit: 'Credit',
    vendor: vendorList[67],
    category: 'mobile',
    type: CreditType.money,
    price: 70,
    points: 10,
    discount: 8,
    isPromo: true,
    timeleft: '2h 30m',
  ),
  Credit(
    id: '8',
    amount: 80,
    description: '30 Days',
    thumb: ImgApi.photo[328],
    unit: 'Credit',
    vendor: vendorList[67],
    category: 'mobile',
    type: CreditType.money,
    price: 80,
    points: 10,
  ),
  Credit(
    id: '9',
    amount: 90,
    description: '30 Days',
    thumb: ImgApi.photo[328],
    unit: 'Credit',
    vendor: vendorList[67],
    category: 'mobile',
    type: CreditType.money,
    price: 90,
    points: 10,
    discount: 5,
    isPromo: true,
    timeleft: '2h 30m',
  ),
  Credit(
    id: '10',
    amount: 100,
    description: '30 Days',
    thumb: ImgApi.photo[328],
    unit: 'Credit',
    vendor: vendorList[67],
    category: 'mobile',
    type: CreditType.money,
    price: 100,
    points: 10,
    discount: 5,
    isPromo: true,
    timeleft: '2h 30m',
  ),
  Credit(
    id: '11',
    amount: 120,
    description: '30 Days',
    thumb: ImgApi.photo[328],
    vendor: vendorList[67],
    unit: 'Credit',
    category: 'mobile',
    type: CreditType.money,
    price: 120,
    points: 10,
    discount: 5,
    isPromo: true,
    timeleft: '2h 30m',
  ),
  Credit(
    id: '12',
    amount: 150,
    description: '30 Days',
    thumb: ImgApi.photo[328],
    vendor: vendorList[67],
    unit: 'Credit',
    category: 'mobile',
    type: CreditType.money,
    price: 150,
    points: 10,
    discount: 5,
    isPromo: true,
    timeleft: '2h 30m',
  )
];