import 'package:ewallet_app/constants/img_api.dart';
import 'package:ewallet_app/models/vendor.dart';

class Package {
  final String id;
  final String name;
  final String images;
  final String thumb;
  final Vendor? vendor;
  final String category;
  final String? groupName;
  final String description;
  final bool isPromo;
  final double price;
  final double discount;
  final List<String>? features;
  final double? points;
  final String? timeleft;
  

  Package({
    required this.id,
    required this.name,
    required this.images,
    required this.thumb,
    this.vendor,
    required this.category,
    this.groupName,
    required this.description,
    this.isPromo = false,
    required this.price,
    this.discount = 0,
    this.features,
    this.points,
    this.timeleft,
  });
}

final List<Package> appPackages = [
  Package(
    id: '1',
    name: 'Starter',
    images: ImgApi.photo[14],
    thumb: ImgApi.photo[24],
    vendor: vendorList[0],
    category: 'app',
    description: 'Quisque vel risus ac ligula ultricies fermentum a id turpis',
    price: 5,
    discount: 10,
    features: ['Unlimited', 'Support', '1 TB'],
    points: 100,
    timeleft: '2d 22h',
  ),
  Package(
    id: '2',
    name: 'Student',
    images: ImgApi.photo[12],
    thumb: ImgApi.photo[22],
    vendor: vendorList[0],
    category: 'app',
    description: 'Cras vulputate, sapien in elementum blandit, augue ipsum ornare sem, non lobortis ipsum diam id justo',
    isPromo: true,
    price: 10,
    discount: 5,
    features: ['Verified', 'Discount', 'Free Cancelation'],
    points: 100,
  ),
  Package(
    id: '3',
    name: 'Family',
    images: ImgApi.photo[16],
    thumb: ImgApi.photo[26],
    vendor: vendorList[0],
    category: 'app',
    description: 'Quisque vel risus ac ligula ultricies fermentum a id turpis',
    isPromo: true,
    price: 12,
    discount: 10,
    features: ['4 Accounts', 'Support', '2 TB'],
    points: 100,
  ),
  Package(
    id: '4',
    name: 'Pro',
    images: ImgApi.photo[15],
    thumb: ImgApi.photo[25],
    vendor: vendorList[0],
    category: 'app',
    description: 'Aliquam urna urna, fermentum id tempor quis, dictum luctus sapien',
    price: 15,
    discount: 20,
    features: ['Unlimited', 'Booster', 'AI Generator'],
    points: 100,
    timeleft: '1d 12h',
  ),
  Package(
    id: '5',
    name: 'Teams',
    images: ImgApi.photo[19],
    thumb: ImgApi.photo[29],
    vendor: vendorList[0],
    category: 'app',
    description: 'Etiam non mi consequat lacus malesuada mattis sit amet vel nisi.',
    price: 25,
    discount: 10,
    features: ['Unlimited', 'Reporting', 'Admin'],
    timeleft: '2d 22h',
  ),
  Package(
    id: '6',
    name: 'Enterprise',
    images: ImgApi.photo[11],
    thumb: ImgApi.photo[21],
    vendor: vendorList[0],
    category: 'app',
    description: 'Nunc ornare erat ligula, sit amet sodales felis laoreet et',
    isPromo: true,
    price: 50,
    discount: 10,
    features: ['Unlimited', 'Private', 'Ai Generator'],
    timeleft: '2d 22h',
  ),
  Package(
    id: '7',
    name: 'Developer',
    images: ImgApi.photo[20],
    thumb: ImgApi.photo[30],
    vendor: vendorList[0],
    category: 'app',
    description: 'Donec nec scelerisque purus. Nam et felis mi. Morbi porta urna eu felis faucibus mattis.',
    isPromo: true,
    price: 50,
    discount: 10,
    features: ['SSO', 'Private Server', 'Integration'],
    timeleft: '2d 22h',
  ),
];

final List<Package> educationPackages = [
  /// Package 1
  Package(
    id: '1',
    name: 'Master of Business Administration',
    images: ImgApi.photo[42],
    thumb: ImgApi.photo[52],
    vendor: vendorList[12],
    category: 'education',
    groupName: 'MBA',
    description: 'Quisque vel risus ac ligula ultricies fermentum a id turpis',
    price: 50,
    discount: 10,
    features: ['1 Year', 'All Devices'],
    points: 100,
    timeleft: '1d 1h',
    isPromo: true
  ),
  Package(
    id: '2',
    name: 'Master of Business Administration',
    images: ImgApi.photo[42],
    thumb: ImgApi.photo[52],
    vendor: vendorList[12],
    category: 'education',
    groupName: 'MBA',
    description: 'Quisque vel risus ac ligula ultricies fermentum a id turpis',
    price: 15,
    discount: 10,
    features: ['3 Month', 'Mobile Only'],
    points: 50,
    timeleft: '1d 1h',
    isPromo: true
  ),
  Package(
    id: '3',
    name: 'Master of Business Administration',
    images: ImgApi.photo[42],
    thumb: ImgApi.photo[52],
    vendor: vendorList[12],
    category: 'education',
    groupName: 'MBA',
    description: 'Quisque vel risus ac ligula ultricies fermentum a id turpis',
    price: 10,
    features: ['1 Month', 'Web Only'],
    points: 10,
  ),
  /// Package 2
  Package(
    id: '4',
    name: 'The Complete Prompt Engineering for AI',
    images: ImgApi.photo[41],
    thumb: ImgApi.photo[51],
    vendor: vendorList[12],
    category: 'education',
    groupName: 'Learn AI',
    description: 'Donec molestie, risus ut placerat tempor, massa ligula elementum arcu, vitae gravida ante elit at ex.',
    price: 50,
    discount: 10,
    features: ['1 Year', 'Free E-Book'],
    points: 100,
    isPromo: true,
    timeleft: '1d 1h',
  ),
  Package(
    id: '5',
    name: 'The Complete Prompt Engineering for AI',
    images: ImgApi.photo[41],
    thumb: ImgApi.photo[51],
    vendor: vendorList[12],
    category: 'education',
    groupName: 'Learn AI',
    description: 'Donec molestie, risus ut placerat tempor, massa ligula elementum arcu, vitae gravida ante elit at ex.',
    price: 5,
    discount: 10,
    features: ['1 Month', 'Free E-Book'],
    points: 100,
    isPromo: true,
    timeleft: '1d 1h',
  ),
  /// Package 3
  Package(
    id: '6',
    name: 'Become an Algebra Master',
    images: ImgApi.photo[48],
    thumb: ImgApi.photo[58],
    vendor: vendorList[12],
    category: 'education',
    groupName: 'Math',
    description: 'Vestibulum cursus cursus diam, et vestibulum nunc rhoncus sed.',
    price: 10,
    features: ['Basic', 'Free E-Book'],
    points: 100,
  ),
  Package(
    id: '7',
    name: 'Become an Algebra Master',
    images: ImgApi.photo[48],
    thumb: ImgApi.photo[58],
    vendor: vendorList[12],
    category: 'education',
    groupName: 'Math',
    description: 'Vestibulum cursus cursus diam, et vestibulum nunc rhoncus sed.',
    price: 10,
    features: ['Intermediate', '3 Languages'],
    points: 100,
  ),
  Package(
    id: '8',
    name: 'Become an Algebra Master',
    images: ImgApi.photo[48],
    thumb: ImgApi.photo[58],
    vendor: vendorList[12],
    category: 'education',
    groupName: 'Math',
    description: 'Vestibulum cursus cursus diam, et vestibulum nunc rhoncus sed',
    price: 20,
    features: ['Advanced', 'Certificate'],
    points: 100,
  ),
  /// Package 4
  Package(
    id: '9',
    name: 'Basics of Financial Markets',
    images: ImgApi.photo[50],
    thumb: ImgApi.photo[60],
    vendor: vendorList[12],
    category: 'education',
    groupName: 'Finance',
    description: 'Suspendisse semper eros commodo, vestibulum enim nec',
    price: 10,
    features: ['1 Month', 'Free E-Book'],
    points: 100,
  ),
  Package(
    id: '10',
    name: 'Basics of Financial Markets',
    images: ImgApi.photo[50],
    thumb: ImgApi.photo[60],
    vendor: vendorList[12],
    category: 'education',
    groupName: 'Finance',
    description: 'Suspendisse semper eros commodo, vestibulum enim nec',
    price: 10,
    features: ['1 Year', '5 Languages'],
    points: 100,
    isPromo: true,
    discount: 20
  ),
  /// Package 5
  Package(
    id: '11',
    name: 'Introduction to Teaching English',
    images: ImgApi.photo[46],
    thumb: ImgApi.photo[56],
    vendor: vendorList[12],
    category: 'education',
    groupName: 'English',
    description: 'Suspendisse semper eros commodo, vestibulum enim nec',
    price: 5,
    features: ['5 Videos', '5 Articles'],
    points: 100,
  ),
  Package(
    id: '12',
    name: 'Introduction to Teaching English',
    images: ImgApi.photo[46],
    thumb: ImgApi.photo[56],
    vendor: vendorList[12],
    category: 'education',
    groupName: 'English',
    description: 'Suspendisse semper eros commodo, vestibulum enim nec',
    price: 10,
    features: ['10 Videos', '5 Articles'],
    points: 100,
  ),
  Package(
    id: '13',
    name: 'Introduction to Teaching English',
    images: ImgApi.photo[46],
    thumb: ImgApi.photo[56],
    vendor: vendorList[12],
    category: 'education',
    groupName: 'English',
    description: 'Suspendisse semper eros commodo, vestibulum enim nec',
    price: 15,
    features: ['15 Videos', '10 Articles'],
    points: 100,
  ),
  Package(
    id: '14',
    name: 'All About the Alphabet',
    images: ImgApi.photo[44],
    thumb: ImgApi.photo[54],
    vendor: vendorList[12],
    category: 'education',
    groupName: 'English',
    description: 'Quisque ultrices fermentum nunc ac gravida',
    price: 10,
    isPromo: true,
    discount: 20,
    features: ['10 Videos', '10 Articles'],
    points: 100,
  ),
  Package(
    id: '15',
    name: 'All About the Alphabet',
    images: ImgApi.photo[44],
    thumb: ImgApi.photo[54],
    vendor: vendorList[12],
    category: 'education',
    groupName: 'English',
    description: 'Quisque ultrices fermentum nunc ac gravida',
    price: 20,
    isPromo: true,
    discount: 25,
    features: ['20 Videos', '20 Articles'],
    points: 100,
  ),
];

final List<Package> entertainmentPackages = [
  Package(
    id: '0',
    name: 'Movie and Series',
    images: ImgApi.photo[85],
    thumb: ImgApi.photo[95],
    vendor: vendorList[21],
    category: 'entertainment',
    description: 'Quisque ultrices fermentum nunc ac gravida',
    price: 20,
    isPromo: true,
    discount: 25,
    features: ['Offline', '4K', 'Ad-Free'],
    points: 100,
  ),
  Package(
    id: '1',
    name: 'Podcast and Talk Show',
    images: ImgApi.photo[81],
    thumb: ImgApi.photo[91],
    vendor: vendorList[21],
    category: 'entertainment',
    description: 'Quisque ultrices fermentum nunc ac gravida',
    price: 20,
    isPromo: true,
    discount: 25,
    features: ['Offline', '4K', 'Ad-Free'],
    points: 100,
  ),
  Package(
    id: '2',
    name: 'Horror Podcast',
    images: ImgApi.photo[82],
    thumb: ImgApi.photo[92],
    vendor: vendorList[21],
    category: 'entertainment',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla.',
    price: 20,
    isPromo: true,
    discount: 25,
    features: ['Offline', '4K', 'Ad-Free'],
    points: 100,
  ),
  Package(
    id: '3',
    name: 'Sport',
    images: ImgApi.photo[83],
    thumb: ImgApi.photo[93],
    vendor: vendorList[21],
    category: 'entertainment',
    description: 'Cras egestas at tortor ut feugiat. Cras vel felis vel ligula blandit pretium ac et lectus.',
    price: 20,
    isPromo: true,
    discount: 25,
    features: ['Offline', '4K', 'Ad-Free'],
    points: 100,
  ),
  Package(
    id: '4',
    name: 'Live Music',
    images: ImgApi.photo[87],
    thumb: ImgApi.photo[97],
    vendor: vendorList[21],
    category: 'entertainment',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla.',
    price: 20,
    isPromo: true,
    discount: 25,
    features: ['Offline', '4K', 'Ad-Free'],
    points: 100,
  ),
  Package(
    id: '5',
    name: 'News',
    images: ImgApi.photo[88],
    thumb: ImgApi.photo[98],
    vendor: vendorList[21],
    category: 'entertainment',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla.',
    price: 20,
    isPromo: true,
    discount: 25,
    features: ['Offline', '4K', 'Ad-Free'],
    points: 100,
  ),
  Package(
    id: '6',
    name: 'Stand Up Comedy',
    images: ImgApi.photo[89],
    thumb: ImgApi.photo[99],
    vendor: vendorList[21],
    category: 'entertainment',
    description: 'Cras egestas at tortor ut feugiat. Cras vel felis vel ligula blandit pretium ac et lectus.',
    price: 20,
    isPromo: true,
    discount: 25,
    features: ['Offline', '4K', 'Ad-Free'],
    points: 100,
  ),
  Package(
    id: '7',
    name: 'Live Music',
    images: ImgApi.photo[90],
    thumb: ImgApi.photo[100],
    vendor: vendorList[21],
    category: 'entertainment',
    description: 'Quisque ultrices fermentum nunc ac gravida',
    price: 10,
    isPromo: true,
    discount: 25,
    features: ['Audio Only', 'Ad-Free'],
    points: 100,
  ),
  Package(
    id: '8',
    name: 'Podcast and Talk Show',
    images: ImgApi.photo[81],
    thumb: ImgApi.photo[91],
    vendor: vendorList[21],
    category: 'entertainment',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla.',
    price: 10,
    features: ['Offline', 'Audio Only'],
    points: 50,
  ),
];

final List<Package> gamePackages = [
  Package(
    id: '1a',
    name: 'Cartoon Skins for King',
    images: ImgApi.photo[111],
    thumb: ImgApi.photo[121],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Skins',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla.',
    price: 20,
    isPromo: true,
    discount: 10,
    features: ['Skin', 'Legendary', 'Limited'],
    points: 100,
    timeleft: '1d 1h',
  ),
  Package(
    id: '1b',
    name: 'Cartoon Skins for Queen',
    images: ImgApi.photo[111],
    thumb: ImgApi.photo[121],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Skins',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla.',
    price: 20,
    isPromo: true,
    discount: 10,
    features: ['Skin', 'Legendary', 'Limited'],
    points: 100,
    timeleft: '1d 1h',
  ),
  Package(
    id: '1c',
    name: 'Cartoon Skins for Princess',
    images: ImgApi.photo[111],
    thumb: ImgApi.photo[121],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Skins',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla.',
    price: 20,
    isPromo: true,
    discount: 10,
    features: ['Skin', 'Legendary', 'Limited'],
    points: 100,
    timeleft: '1d 1h',
  ),
  Package(
    id: '2a',
    name: 'Space Stickers',
    images: ImgApi.photo[112],
    thumb: ImgApi.photo[122],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Stickers',
    description: 'Cras egestas at tortor ut feugiat. Cras vel felis vel ligula blandit pretium ac et lectus.',
    price: 5,
    features: ['10 Stickers', 'Permanent'],
    points: 100,
  ),
  Package(
    id: '2b',
    name: 'Space Stickers',
    images: ImgApi.photo[112],
    thumb: ImgApi.photo[122],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Stickers',
    description: 'Cras egestas at tortor ut feugiat. Cras vel felis vel ligula blandit pretium ac et lectus.',
    price: 8,
    features: ['20 Stickers', 'Permanent'],
    points: 100,
  ),
  Package(
    id: '2c',
    name: 'Space Stickers',
    images: ImgApi.photo[112],
    thumb: ImgApi.photo[122],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Stickers',
    description: 'Cras egestas at tortor ut feugiat. Cras vel felis vel ligula blandit pretium ac et lectus.',
    price: 20,
    features: ['All(100) Stickers', 'Permanent'],
    points: 100,
  ),
  Package(
    id: '3',
    name: 'Football Event Pass',
    images: ImgApi.photo[113],
    thumb: ImgApi.photo[123],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Event',
    description: 'Donec interdum commodo aliquet',
    price: 5,
    features: ['Event Pass', 'Free Skin'],
    points: 100,
  ),
  Package(
    id: '4',
    name: 'Trivia Quiz Event',
    images: ImgApi.photo[114],
    thumb: ImgApi.photo[124],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Event',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla.',
    price: 20,
    isPromo: true,
    discount: 10,
    features: ['Event Pass', 'Free Skin', 'Limited'],
    points: 100,
    timeleft: '1d 1h',
  ),
  Package(
    id: '5a',
    name: 'Sport Car Black Skin',
    images: ImgApi.photo[115],
    thumb: ImgApi.photo[125],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Skins',
    description: 'Cras egestas at tortor ut feugiat. Cras vel felis vel ligula blandit pretium ac et lectus.',
    price: 5,
    features: ['Skin', 'Permanent', 'Limited'],
    points: 100,
  ),
  Package(
    id: '5b',
    name: 'Sport Car Red Skin',
    images: ImgApi.photo[115],
    thumb: ImgApi.photo[125],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Skins',
    description: 'Cras egestas at tortor ut feugiat. Cras vel felis vel ligula blandit pretium ac et lectus.',
    price: 5,
    features: ['Skin', 'Permanent', 'Limited'],
    points: 100,
  ),
  Package(
    id: '6',
    name: 'Space Background',
    images: ImgApi.photo[116],
    thumb: ImgApi.photo[126],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Theme',
    description: 'Donec interdum commodo aliquet',
    price: 5,
    features: ['Theme', 'Legendary'],
    points: 100,
  ),
  Package(
    id: '7a',
    name: 'NCE Robot Female Costum',
    images: ImgApi.photo[117],
    thumb: ImgApi.photo[127],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Skins',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla.',
    price: 20,
    isPromo: true,
    discount: 10,
    features: ['Skin', 'Common'],
    points: 100,
    timeleft: '1d 1h',
  ),
  Package(
    id: '7b',
    name: 'NCE Robot Male Costum',
    images: ImgApi.photo[117],
    thumb: ImgApi.photo[127],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Skins',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla.',
    price: 20,
    isPromo: true,
    discount: 10,
    features: ['Skin', 'Common'],
    points: 100,
    timeleft: '1d 1h',
  ),
  Package(
    id: '8',
    name: 'Volleyball Event',
    images: ImgApi.photo[118],
    thumb: ImgApi.photo[128],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Event',
    description: 'Donec interdum commodo aliquet',
    price: 5,
    features: ['Event Pass', 'Bonuses'],
    points: 100,
  ),
  Package(
    id: '9a',
    name: 'Football Stickers',
    images: ImgApi.photo[119],
    thumb: ImgApi.photo[129],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Stickers',
    description: 'Donec interdum commodo aliquet',
    price: 5,
    features: ['10 Stickers', 'Limited', 'Legendary'],
    points: 100,
  ),
  Package(
    id: '9b',
    name: 'Football Stickers',
    images: ImgApi.photo[119],
    thumb: ImgApi.photo[129],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Stickers',
    description: 'Donec interdum commodo aliquet',
    price: 10,
    features: ['50 Sticker', 'Limited', 'Legendary'],
    points: 100,
  ),
  Package(
    id: '9c',
    name: 'Football Stickers',
    images: ImgApi.photo[119],
    thumb: ImgApi.photo[129],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Stickers',
    description: 'Donec interdum commodo aliquet',
    price: 15,
    features: ['All(100) Stickers', 'Limited', 'Legendary'],
    points: 100,
  ),
  Package(
    id: '10',
    name: 'Pixel Background',
    images: ImgApi.photo[120],
    thumb: ImgApi.photo[130],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Theme',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla.',
    price: 20,
    isPromo: true,
    discount: 10,
    features: ['Theme'],
    points: 100,
    timeleft: '1d 1h',
  ),
  Package(
    id: '10',
    name: 'Pixel Background + Skins',
    images: ImgApi.photo[120],
    thumb: ImgApi.photo[130],
    vendor: vendorList[33],
    category: 'game',
    groupName: 'Theme',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla.',
    price: 25,
    isPromo: true,
    discount: 10,
    features: ['Background', 'Skins'],
    points: 100,
    timeleft: '1d 1h',
  ),
];

final List<Package> mobilePackages = [
  /// Package 1
  Package(
    id: '1',
    name: 'Regular Internet Package',
    images: ImgApi.photo[181],
    thumb: ImgApi.photo[191],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Internet',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla',
    price: 20,
    isPromo: true,
    discount: 10,
    features: ['7 Days', '10GB'],
    points: 100,
    timeleft: '1d 1h',
  ),
  Package(
    id: '2',
    name: 'Regular Internet Package',
    images: ImgApi.photo[181],
    thumb: ImgApi.photo[191],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Internet',
    description: 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos',
    price: 30,
    features: ['1 Month', '100GB'],
    points: 100,
  ),
  Package(
    id: '3',
    name: 'Regular Internet Package',
    images: ImgApi.photo[181],
    thumb: ImgApi.photo[191],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Internet',
    description: 'Aliquam nec laoreet diam, ut convallis ipsum',
    price: 40,
    isPromo: true,
    discount: 10,
    features: ['1 Month', '150GB'],
    points: 100,
    timeleft: '1d 1h',
  ),
  /// Package 2
  Package(
    id: '4',
    name: 'Combo Internet Package',
    images: ImgApi.photo[182],
    thumb: ImgApi.photo[192],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Combo Internet',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla',
    price: 20,
    features: ['7 Days', '10GB Data', '2GB Social Apps'],
    points: 100,
  ),
  Package(
    id: '5',
    name: 'Combo Internet Package',
    images: ImgApi.photo[182],
    thumb: ImgApi.photo[192],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Combo Internet',
    description: 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos',
    price: 30,
    features: ['1 Month', '90GB Data', '10GB Streaming'],
    points: 100,
  ),
  Package(
    id: '6',
    name: 'Combo Internet Package',
    images: ImgApi.photo[182],
    thumb: ImgApi.photo[192],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Combo Internet',
    description: 'Aliquam nec laoreet diam, ut convallis ipsum',
    price: 40,
    isPromo: true,
    discount: 10,
    features: ['1 Month', '150GB Data', '50GB Night Quota'],
    points: 100,
    timeleft: '1d 1h',
  ),
  /// Package 3
  Package(
    id: '7',
    name: 'Call and SMS Package',
    images: ImgApi.photo[190],
    thumb: ImgApi.photo[200],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'SMS & Call',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla',
    price: 5,
    features: ['7 Days', '200 Minutes', '50 SMS'],
    points: 100,
  ),
  Package(
    id: '8',
    name: 'Call and SMS Package',
    images: ImgApi.photo[190],
    thumb: ImgApi.photo[200],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'SMS & Call',
    description: 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos',
    price: 30,
    features: ['1 Month', 'Unlimited Call', '100 SMS'],
    points: 100,
  ),
  Package(
    id: '9',
    name: 'Call and SMS Package',
    images: ImgApi.photo[190],
    thumb: ImgApi.photo[200],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'SMS & Call',
    description: 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos',
    price: 30,
    features: ['1 Month', 'Unlimited Call', '100 SMS'],
    points: 100,
  ),
  Package(
    id: '10',
    name: 'Call and SMS Package',
    images: ImgApi.photo[190],
    thumb: ImgApi.photo[200],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'SMS & Call',
    description: 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos',
    price: 30,
    features: ['1 Month', 'Unlimited Call', '100 SMS'],
    points: 100,
  ),
  /// Package 4
  Package(
    id: '11',
    name: 'International Roaming',
    images: ImgApi.photo[188],
    thumb: ImgApi.photo[198],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Roaming',
    description: 'Praesent nisi sem, hendrerit ac purus vel, scelerisque molestie nulla',
    price: 20,
    features: ['3 Days', '5GB Data', '60 Minutes Call'],
    points: 100,
  ),
  Package(
    id: '12',
    name: 'International Roaming',
    images: ImgApi.photo[188],
    thumb: ImgApi.photo[198],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Roaming',
    description: 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos',
    price: 30,
    features: ['7 Days', '10GB Data', '120 Minutes Call'],
    points: 100,
  ),
  Package(
    id: '13',
    name: 'International Roaming',
    images: ImgApi.photo[188],
    thumb: ImgApi.photo[198],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Roaming',
    description: 'Aliquam nec laoreet diam, ut convallis ipsum',
    price: 60,
    isPromo: true,
    discount: 10,
    features: ['20 Days', '50GB Data', '360 Minutes Call'],
    points: 100,
    timeleft: '1d 1h',
  ),
  /// Package 5
  Package(
    id: '14',
    name: 'Work and Education',
    images: ImgApi.photo[183],
    thumb: ImgApi.photo[193],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Work Education',
    description: 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos',
    price: 60,
    isPromo: true,
    discount: 10,
    features: ['50GB Data', '360 Minutes Video Call', 'Unlimited Apps'],
    points: 100,
    timeleft: '1d 1h',
  ),
  Package(
    id: '15',
    name: 'First Class',
    images: ImgApi.photo[184],
    thumb: ImgApi.photo[194],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Unlimited',
    description: 'Fusce libero massa, imperdiet eget lectus sit amet, mollis feugiat nulla. Morbi cursus lacinia mollis.',
    price: 120,
    isPromo: true,
    discount: 10,
    features: ['Unlimited Data', 'Max Speed 10Mbps'],
    points: 100,
    timeleft: '1d 1h',
  ),
  Package(
    id: '16',
    name: 'Freedom',
    images: ImgApi.photo[186],
    thumb: ImgApi.photo[196],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Unlimited',
    description: 'Aliquam nec laoreet diam, ut convallis ipsum',
    price: 60,
    features: ['Unlimited Data', 'Max Speed 1Mbps'],
    points: 100,
  ),
  Package(
    id: '17',
    name: 'Double Freedom',
    images: ImgApi.photo[186],
    thumb: ImgApi.photo[196],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Unlimited',
    description: 'Donec non convallis ligula. Etiam aliquam bibendum vestibulum',
    price: 80,
    features: ['Unlimited Data', 'Max Speed 2Mbps'],
    points: 100,
  ),
  Package(
    id: '18',
    name: 'Tablet Device',
    images: ImgApi.photo[185],
    thumb: ImgApi.photo[195],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Flexible',
    description: 'Fusce libero massa, imperdiet eget lectus sit amet, mollis feugiat nulla. Morbi cursus lacinia mollis',
    price: 10,
    features: ['1 Month', '100GB'],
    points: 100,
  ),
  Package(
    id: '19',
    name: 'Team Plan',
    images: ImgApi.photo[187],
    thumb: ImgApi.photo[197],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Flexible',
    description: 'Morbi feugiat rhoncus purus a scelerisque. Nullam sed vehicula sem, eu malesuada elit',
    price: 100,
    features: ['1 Month', '4 Members' '100GB/Member'],
    points: 100,
  ),
  Package(
    id: '20',
    name: 'Family Plan',
    images: ImgApi.photo[189],
    thumb: ImgApi.photo[199],
    vendor: vendorList[63],
    category: 'mobile',
    groupName: 'Flexible',
    description: 'Vestibulum cursus cursus diam, et vestibulum nunc rhoncus sed',
    price: 50,
    features: ['1 Month', '4 Members', '40GB/Member'],
    points: 100,
  ),
];
