import 'package:ewallet_app/constants/img_api.dart';

class Vendor {

  final String id;
  final String logo;
  final String name;
  final String? description;
  final bool hasPromo;
  final String? category;
  final String? banner;

  Vendor({
    required this.id,
    required this.logo,
    required this.name,
    this.hasPromo = false,
    this.description,
    this.category,
    this.banner
  });
}

List<Vendor> appVendors = [
  Vendor(
    id: '1',
    logo: ImgApi.photo[261],
    banner: ImgApi.photo[2],
    name: 'Skills',
    hasPromo: true,
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '2',
    logo: ImgApi.photo[262],
    banner: ImgApi.photo[1],
    name: 'Mode',
    hasPromo: true,
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '3',
    logo: ImgApi.photo[263],
    banner: ImgApi.photo[10],
    name: 'Tech House',
    hasPromo: true,
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '4',
    logo: ImgApi.photo[264],
    banner: ImgApi.photo[4],
    name: 'Ondev Apps',
    hasPromo: true,
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '5',
    logo: ImgApi.photo[265],
    banner: ImgApi.photo[5],
    name: 'Wardiere Software',
    hasPromo: true,
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '6',
    logo: ImgApi.photo[266],
    banner: ImgApi.photo[3],
    name: 'Arrowwai AI',
    hasPromo: true,
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '7',
    logo: ImgApi.photo[267],
    banner: ImgApi.photo[8],
    name: 'Aldenaire Creative Cloud',
    hasPromo: true,
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '8',
    logo: ImgApi.photo[268],
    banner: ImgApi.photo[6],
    name: 'Wewewedot Apps',
    hasPromo: true,
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '9',
    logo: ImgApi.photo[269],
    banner: ImgApi.photo[9],
    name: 'Open Box',
    hasPromo: true,
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '10',
    logo: ImgApi.photo[270],
    banner: ImgApi.photo[7],
    name: 'Aldenaire Docs',
    hasPromo: true,
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
];

List<Vendor> educationVendors = [
  Vendor(
    id: '1',
    logo: ImgApi.photo[271],
    banner: ImgApi.photo[37],
    name: 'Rimberio Online School',
    hasPromo: true,
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '2',
    logo: ImgApi.photo[272],
    banner: ImgApi.photo[32],
    name: 'Kidos',
    hasPromo: true,
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '3',
    logo: ImgApi.photo[273],
    banner: ImgApi.photo[34],
    name: 'Tech Connect',
    hasPromo: true,
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '4',
    logo: ImgApi.photo[274],
    banner: ImgApi.photo[31],
    name: 'Kiberlys Design Studio',
    hasPromo: true,
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '5',
    logo: ImgApi.photo[275],
    banner: ImgApi.photo[35],
    name: 'Skills',
    hasPromo: true,
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '6',
    logo: ImgApi.photo[276],
    banner: ImgApi.photo[38],
    name: 'Mode',
    hasPromo: true,
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '7',
    logo: ImgApi.photo[277],
    banner: ImgApi.photo[34],
    name: 'Tech House',
    hasPromo: true,
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '8',
    logo: ImgApi.photo[278],
    banner: ImgApi.photo[33],
    name: 'Online Course',
    hasPromo: true,
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '9',
    logo: ImgApi.photo[279],
    banner: ImgApi.photo[39],
    name: 'Fouget Course',
    hasPromo: true,
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '10',
    logo: ImgApi.photo[280],
    banner: ImgApi.photo[40],
    name: 'West Shores School Business',
    hasPromo: true,
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
];

List<Vendor> entertainmentVendors = [
  Vendor(
    id: '1',
    logo: ImgApi.photo[281],
    banner: ImgApi.photo[72],
    name: 'Savage Studio',
    hasPromo: true,
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '2',
    logo: ImgApi.photo[282],
    banner: ImgApi.photo[71],
    name: 'LMTV',
    hasPromo: true,
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '3',
    logo: ImgApi.photo[283],
    banner: ImgApi.photo[75],
    name: 'Spies Sport',
    hasPromo: true,
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '4',
    logo: ImgApi.photo[284],
    banner: ImgApi.photo[73],
    name: 'News Times',
    hasPromo: true,
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '5',
    logo: ImgApi.photo[285],
    banner: ImgApi.photo[78],
    name: 'Avery Kids',
    hasPromo: true,
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '6',
    logo: ImgApi.photo[286],
    banner: ImgApi.photo[77],
    name: 'Studio Shodwe',
    hasPromo: true,
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '7',
    logo: ImgApi.photo[287],
    banner: ImgApi.photo[80],
    name: 'Retro',
    hasPromo: true,
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '8',
    logo: ImgApi.photo[288],
    banner: ImgApi.photo[79],
    name: 'Cineount Picture',
    hasPromo: true,
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '9',
    logo: ImgApi.photo[289],
    banner: ImgApi.photo[76],
    name: 'Live Stream',
    hasPromo: true,
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '10',
    logo: ImgApi.photo[290],
    banner: ImgApi.photo[74],
    name: 'Mojo',
    hasPromo: true,
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
];

List<Vendor> gameVendors = [
  Vendor(
    id: '1',
    logo: ImgApi.photo[291],
    banner: ImgApi.photo[101],
    name: 'Borcelle',
    hasPromo: true,
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '2',
    logo: ImgApi.photo[292],
    banner: ImgApi.photo[102],
    name: 'Blank Box',
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '3',
    logo: ImgApi.photo[293],
    banner: ImgApi.photo[107],
    name: 'Fauget Game Deluxe',
    hasPromo: true,
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '4',
    logo: ImgApi.photo[294],
    banner: ImgApi.photo[103],
    name: 'Liceria',
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '5',
    logo: ImgApi.photo[295],
    banner: ImgApi.photo[105],
    name: 'Tennis Club Championship',
    hasPromo: true,
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '6',
    logo: ImgApi.photo[296],
    banner: ImgApi.photo[109],
    name: 'Race Flag 2026',
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '7',
    logo: ImgApi.photo[297],
    banner: ImgApi.photo[104],
    name: 'Helicoprion',
    hasPromo: true,
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '8',
    logo: ImgApi.photo[298],
    banner: ImgApi.photo[108],
    name: 'Soldier of Tomorrow',
    hasPromo: true,
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '9',
    logo: ImgApi.photo[299],
    banner: ImgApi.photo[106],
    name: 'The Monkey Surprise',
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '10',
    logo: ImgApi.photo[300],
    banner: ImgApi.photo[110],
    name: 'Warner Playground',
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
];

List<Vendor> internetVendors = [
  Vendor(
    id: '1',
    logo: ImgApi.photo[301],
    banner: ImgApi.photo[131],
    name: 'Infocom',
    hasPromo: true,
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '2',
    logo: ImgApi.photo[302],
    banner: ImgApi.photo[135],
    name: 'Fauget',
    hasPromo: true,
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '3',
    logo: ImgApi.photo[303],
    banner: ImgApi.photo[133],
    name: 'Infinity',
    hasPromo: true,
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '4',
    logo: ImgApi.photo[304],
    banner: ImgApi.photo[136],
    name: 'Digital World',
    hasPromo: true,
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '5',
    logo: ImgApi.photo[305],
    banner: ImgApi.photo[132],
    name: 'Salford',
    hasPromo: true,
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '6',
    logo: ImgApi.photo[306],
    banner: ImgApi.photo[140],
    name: 'Aldenaire',
    hasPromo: true,
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '7',
    logo: ImgApi.photo[307],
    banner: ImgApi.photo[134],
    name: 'Loop',
    hasPromo: true,
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '8',
    logo: ImgApi.photo[308],
    banner: ImgApi.photo[137],
    name: 'Network Tagline',
    hasPromo: true,
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '9',
    logo: ImgApi.photo[309],
    banner: ImgApi.photo[138],
    name: 'Tech World',
    hasPromo: true,
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '10',
    logo: ImgApi.photo[310],
    banner: ImgApi.photo[139],
    name: 'XL Net',
    hasPromo: true,
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
];

List<Vendor> medicalVendors = [
  Vendor(
    id: '1',
    logo: ImgApi.photo[311],
    banner: ImgApi.photo[151],
    name: 'Medical Care',
    hasPromo: true,
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '2',
    logo: ImgApi.photo[312],
    banner: ImgApi.photo[152],
    name: 'Prime Care',
    hasPromo: true,
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '3',
    logo: ImgApi.photo[313],
    banner: ImgApi.photo[153],
    name: 'Medical Insurance',
    hasPromo: true,
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '4',
    logo: ImgApi.photo[314],
    banner: ImgApi.photo[154],
    name: 'Shield Insurance',
    hasPromo: true,
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '5',
    logo: ImgApi.photo[315],
    banner: ImgApi.photo[155],
    name: 'Fauget Medical',
    hasPromo: true,
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '6',
    logo: ImgApi.photo[316],
    banner: ImgApi.photo[160],
    name: 'Aldenaire Insurance',
    hasPromo: true,
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '7',
    logo: ImgApi.photo[317],
    banner: ImgApi.photo[157],
    name: 'Home Properties Insurance',
    hasPromo: true,
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '8',
    logo: ImgApi.photo[318],
    banner: ImgApi.photo[158],
    name: 'Family Insurance',
    hasPromo: true,
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '9',
    logo: ImgApi.photo[319],
    banner: ImgApi.photo[159],
    name: 'Guardian Insurance',
    hasPromo: true,
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '10',
    logo: ImgApi.photo[320],
    banner: ImgApi.photo[156],
    name: 'GM Autocars',
    hasPromo: true,
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
];

List<Vendor> mobileVendors = [
  Vendor(
    id: '1',
    logo: ImgApi.photo[321],
    banner: ImgApi.photo[171],
    name: 'Fauget',
    hasPromo: true,
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '2',
    logo: ImgApi.photo[322],
    banner: ImgApi.photo[172],
    name: 'Vertuvi',
    hasPromo: true,
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '3',
    logo: ImgApi.photo[323],
    banner: ImgApi.photo[173],
    name: 'Infinity',
    hasPromo: true,
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '4',
    logo: ImgApi.photo[324],
    banner: ImgApi.photo[174],
    name: 'Borcelle Communication',
    hasPromo: true,
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '5',
    logo: ImgApi.photo[325],
    banner: ImgApi.photo[175],
    name: 'Aldenaire',
    hasPromo: true,
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '6',
    logo: ImgApi.photo[326],
    banner: ImgApi.photo[176],
    name: 'Loop',
    hasPromo: true,
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '7',
    logo: ImgApi.photo[327],
    banner: ImgApi.photo[177],
    name: 'Bolden Communicator',
    hasPromo: true,
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '8',
    logo: ImgApi.photo[328],
    banner: ImgApi.photo[178],
    name: 'XL',
    hasPromo: true,
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '9',
    logo: ImgApi.photo[329],
    banner: ImgApi.photo[179],
    name: 'Fusion',
    hasPromo: true,
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '10',
    logo: ImgApi.photo[330],
    banner: ImgApi.photo[180],
    name: 'Global Cell',
    hasPromo: true,
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
];

List<Vendor> tvVendors = [
  Vendor(
    id: '1',
    logo: ImgApi.photo[331],
    banner: ImgApi.photo[205],
    name: 'Savage Studio',
    hasPromo: true,
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '2',
    logo: ImgApi.photo[332],
    banner: ImgApi.photo[201],
    name: 'LMTV',
    hasPromo: true,
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '3',
    logo: ImgApi.photo[333],
    banner: ImgApi.photo[207],
    name: 'Wardiere',
    hasPromo: true,
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '4',
    logo: ImgApi.photo[334],
    banner: ImgApi.photo[210],
    name: 'Kids Channel',
    hasPromo: true,
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '5',
    logo: ImgApi.photo[335],
    banner: ImgApi.photo[203],
    name: 'Live News',
    hasPromo: true,
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '6',
    logo: ImgApi.photo[336],
    banner: ImgApi.photo[208],
    name: 'Spies Sports',
    hasPromo: true,
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '7',
    logo: ImgApi.photo[337],
    banner: ImgApi.photo[206],
    name: 'Salford Cinema',
    hasPromo: true,
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '8',
    logo: ImgApi.photo[338],
    banner: ImgApi.photo[203],
    name: 'News Times',
    hasPromo: true,
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '9',
    logo: ImgApi.photo[339],
    banner: ImgApi.photo[210],
    name: 'Avery Kids',
    hasPromo: true,
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '10',
    logo: ImgApi.photo[320],
    banner: ImgApi.photo[204],
    name: 'Shodwe',
    hasPromo: true,
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
];

List<Vendor> vendorList = [
  Vendor(
    id: '1',
    logo: ImgApi.photo[261],
    name: 'Skills',
    category: 'apps',
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '2',
    logo: ImgApi.photo[262],
    name: 'Mode',
    hasPromo: true,
    category: 'apps',
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '3',
    logo: ImgApi.photo[263],
    name: 'Tech House',
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '4',
    logo: ImgApi.photo[264],
    name: 'Ondev Apps',
    hasPromo: true,
    category: 'apps',
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '5',
    logo: ImgApi.photo[265],
    name: 'Wardiere Software',
    category: 'apps',
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '6',
    logo: ImgApi.photo[266],
    name: 'Arrowwai AI',
    hasPromo: true,
    category: 'apps',
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '7',
    logo: ImgApi.photo[267],
    name: 'Aldenaire Creative Cloud',
    category: 'apps',
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '8',
    logo: ImgApi.photo[268],
    name: 'Wewewedot Apps',
    hasPromo: true,
    category: 'apps',
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '9',
    logo: ImgApi.photo[269],
    name: 'Open Box',
    category: 'apps',
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '10',
    logo: ImgApi.photo[270],
    name: 'Aldenaire Docs',
    hasPromo: true,
    category: 'apps',
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
  Vendor(
    id: '11',
    logo: ImgApi.photo[271],
    category: 'education',
    name: 'Rimberio Online School',
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '12',
    logo: ImgApi.photo[272],
    name: 'Kidos',
    hasPromo: true,
    category: 'education',
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '13',
    logo: ImgApi.photo[273],
    name: 'Tech Connect',
    category: 'education',
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '14',
    logo: ImgApi.photo[274],
    name: 'Kiberlys Design Studio',
    hasPromo: true,
    category: 'education',
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '15',
    logo: ImgApi.photo[275],
    name: 'Skills',
    category: 'education',
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '16',
    logo: ImgApi.photo[276],
    name: 'Mode',
    hasPromo: true,
    category: 'education',
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '17',
    logo: ImgApi.photo[277],
    name: 'Tech House',
    hasPromo: true,
    category: 'education',
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '18',
    logo: ImgApi.photo[278],
    name: 'Online Course',
    category: 'education',
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '19',
    logo: ImgApi.photo[279],
    name: 'Fouget Course',
    hasPromo: true,
    category: 'education',
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '20',
    logo: ImgApi.photo[280],
    name: 'West Shores School Business',
    category: 'education',
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
  Vendor(
    id: '21',
    logo: ImgApi.photo[281],
    name: 'Savage Studio',
    hasPromo: true,
    category: 'entertainment',
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '22',
    logo: ImgApi.photo[282],
    name: 'LMTV',
    hasPromo: true,
    category: 'entertainment',
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '23',
    logo: ImgApi.photo[283],
    name: 'Spies Sport',
    category: 'entertainment',
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '24',
    logo: ImgApi.photo[284],
    name: 'News Times',
    category: 'entertainment',
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '25',
    logo: ImgApi.photo[285],
    name: 'Avery Kids',
    hasPromo: true,
    category: 'entertainment',
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '26',
    logo: ImgApi.photo[286],
    name: 'Studio Shodwe',
    category: 'entertainment',
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '27',
    logo: ImgApi.photo[287],
    name: 'Retro',
    category: 'entertainment',
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '28',
    logo: ImgApi.photo[288],
    name: 'Cineount Picture',
    hasPromo: true,
    category: 'entertainment',
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '29',
    logo: ImgApi.photo[289],
    name: 'Live Stream',
    hasPromo: true,
    category: 'entertainment',
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '30',
    logo: ImgApi.photo[290],
    name: 'Mojo',
    category: 'entertainment',
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
  Vendor(
    id: '31',
    logo: ImgApi.photo[291],
    name: 'Borcelle',
    hasPromo: true,
    category: 'games',
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '32',
    logo: ImgApi.photo[292],
    name: 'Blank Box',
    category: 'games',
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '33',
    logo: ImgApi.photo[293],
    name: 'Fauget Game',
    hasPromo: true,
    category: 'games',
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '34',
    logo: ImgApi.photo[294],
    name: 'Liceria',
    hasPromo: true,
    category: 'games',
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '35',
    logo: ImgApi.photo[295],
    name: 'Tennis Club Championship',
    hasPromo: true,
    category: 'games',
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '36',
    logo: ImgApi.photo[296],
    name: 'Race Flag',
    category: 'games',
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '37',
    logo: ImgApi.photo[297],
    name: 'Helicoprion',
    hasPromo: true,
    category: 'games',
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '38',
    logo: ImgApi.photo[298],
    name: 'SOLDIER',
    category: 'games',
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '39',
    logo: ImgApi.photo[299],
    name: 'Monkey',
    hasPromo: true,
    category: 'games',
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '40',
    logo: ImgApi.photo[300],
    name: 'Warner Playground',
    hasPromo: true,
    category: 'games',
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
  Vendor(
    id: '41',
    logo: ImgApi.photo[301],
    name: 'Infocom',
    hasPromo: true,
    category: 'internet',
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '42',
    logo: ImgApi.photo[302],
    name: 'Fauget',
    category: 'internet',
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '43',
    logo: ImgApi.photo[303],
    name: 'Infinity',
    hasPromo: true,
    category: 'internet',
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '44',
    logo: ImgApi.photo[304],
    name: 'Digital World',
    hasPromo: true,
    category: 'internet',
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '45',
    logo: ImgApi.photo[305],
    name: 'Salford',
    category: 'internet',
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '46',
    logo: ImgApi.photo[306],
    name: 'Aldenaire',
    hasPromo: true,
    category: 'internet',
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '47',
    logo: ImgApi.photo[307],
    name: 'Loop',
    category: 'internet',
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '48',
    logo: ImgApi.photo[308],
    name: 'Network Tagline',
    hasPromo: true,
    category: 'internet',
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '49',
    logo: ImgApi.photo[309],
    name: 'Tech World',
    category: 'internet',
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '50',
    logo: ImgApi.photo[310],
    name: 'XL Net',
    hasPromo: true,
    category: 'internet',
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
  Vendor(
    id: '51',
    logo: ImgApi.photo[311],
    name: 'Medical Care',
    category: 'insurance',
    hasPromo: true,
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '52',
    logo: ImgApi.photo[312],
    name: 'Prime Care',
    category: 'insurance',
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '53',
    logo: ImgApi.photo[313],
    name: 'Medical Insurance',
    category: 'insurance',
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '54',
    logo: ImgApi.photo[314],
    name: 'Shield Insurance',
    hasPromo: true,
    category: 'insurance',
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '55',
    logo: ImgApi.photo[315],
    name: 'Fauget Medical',
    category: 'insurance',
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '56',
    logo: ImgApi.photo[316],
    name: 'Aldenaire Insurance',
    hasPromo: true,
    category: 'insurance',
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '57',
    logo: ImgApi.photo[317],
    name: 'Home Properties Insurance',
    hasPromo: true,
    category: 'insurance',
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '58',
    logo: ImgApi.photo[318],
    name: 'Family Insurance',
    category: 'insurance',
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '59',
    logo: ImgApi.photo[319],
    name: 'Guardian Insurance',
    hasPromo: true,
    category: 'insurance',
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '60',
    logo: ImgApi.photo[320],
    name: 'GM Autocars',
    category: 'insurance',
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
  Vendor(
    id: '61',
    logo: ImgApi.photo[321],
    name: 'Fauget',
    hasPromo: true,
    category: 'mobile',
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '62',
    logo: ImgApi.photo[322],
    name: 'Vertuvi',
    hasPromo: true,
    category: 'mobile',
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '63',
    logo: ImgApi.photo[323],
    name: 'Infinity',
    hasPromo: true,
    category: 'mobile',
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '64',
    logo: ImgApi.photo[324],
    name: 'Borcelle Communication',
    hasPromo: true,
    category: 'mobile',
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '65',
    logo: ImgApi.photo[325],
    name: 'Aldenaire',
    category: 'mobile',
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '66',
    logo: ImgApi.photo[326],
    name: 'Loop',
    hasPromo: true,
    category: 'mobile',
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '67',
    logo: ImgApi.photo[327],
    name: 'Bolden Communicator',
    category: 'mobile',
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '68',
    logo: ImgApi.photo[328],
    name: 'XL',
    hasPromo: true,
    category: 'mobile',
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '69',
    logo: ImgApi.photo[329],
    name: 'Fusion',
    category: 'mobile',
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '70',
    logo: ImgApi.photo[330],
    name: 'Global Cell',
    hasPromo: true,
    category: 'mobile',
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
  Vendor(
    id: '71',
    logo: ImgApi.photo[331],
    name: 'Savage Studio',
    hasPromo: true,
    category: 'tv',
    description: 'Nulla condimentum pulvinar arcu a pellentesque. Pellentesque venenatis molestie diam in laoreet',
  ),
  Vendor(
    id: '72',
    logo: ImgApi.photo[332],
    name: 'LMTV',
    category: 'tv',
    description: 'Donec blandit turpis nulla, nec bibendum urna elementum eget',
  ),
  Vendor(
    id: '73',
    logo: ImgApi.photo[333],
    name: 'Wardiere',
    category: 'tv',
    description: 'Vivamus dui tortor, scelerisque sed scelerisque quis, sollicitudin eu ex',
  ),
  Vendor(
    id: '74',
    logo: ImgApi.photo[334],
    name: 'Kids Channel',
    category: 'tv',
    description: 'Nunc consectetur hendrerit urna. Pellentesque pellentesque lacinia augue eu venenatis. Praesent interdum a purus nec euismod',
  ),
  Vendor(
    id: '75',
    logo: ImgApi.photo[335],
    name: 'Live News',
    category: 'tv',
    description: 'Ut iaculis sapien sit amet quam convallis, in laoreet lorem consequat',
  ),
  Vendor(
    id: '76',
    logo: ImgApi.photo[336],
    name: 'Spies Sports',
    category: 'tv',
    description: 'Integer quis interdum mauris. Integer eget massa posuere, gravida massa ac',
  ),
  Vendor(
    id: '77',
    logo: ImgApi.photo[337],
    name: 'Salford Cinema',
    category: 'tv',
    description: 'Curabitur interdum, arcu sit amet ultrices cursus, tellus est dapibus massa',
  ),
  Vendor(
    id: '78',
    logo: ImgApi.photo[338],
    name: 'News Times',
    category: 'tv',
    description: 'Curabitur eros massa, laoreet et maximus a, facilisis eu enim',
  ),
  Vendor(
    id: '79',
    logo: ImgApi.photo[339],
    name: 'Avery Kids',
    category: 'tv',
    description: 'Nulla suscipit ut lorem at mollis. Phasellus facilisis ex nec magna mattis tempus. Suspendisse facilisis dictum quam.',
  ),
  Vendor(
    id: '80',
    logo: ImgApi.photo[320],
    name: 'Shodwe',
    category: 'tv',
    description: 'Pellentesque scelerisque purus nibh, sit amet vestibulum nulla consectetur at',
  ),
];